---
- name: Make sure newrelic_license_key var has a value
  fail:
    msg: "'newrelic_license_key' is empty or undefined"
  when: newrelic_license_key is undefined
    or newrelic_license_key|trim == ''

- name: Make sure newrelic_app_name var has a value
  fail:
    msg: "'newrelic_app_name' is empty or undefined"
  when: newrelic_app_name is undefined
    or newrelic_app_name|trim == ''

- name: Make sure newrelic_extra_params var has a value
  fail:
    msg: newrelic_extra_params is empty or undefined
  when: newrelic_extra_params is undefined
    or newrelic_extra_params|trim == ''

- name: Install New Relic on Ubuntu
  script: >
    {{ role_path }}/scripts/install-new-relic-ubuntu.sh {{ newrelic_license_key }} "{{ newrelic_app_name }}" {{ newrelic_extra_params }}
  args:
    executable: /bin/bash
  register: command_result
  changed_when: command_result is defined and ("'newly installed' in command_result.stdout or 'Setting up' in command_result.stdout")
  when: ansible_os_family == 'Debian'

- name: Install New Relic on Red Hat
  script: >
    {{ role_path}}/scripts/install-new-relic-redhat.sh {{ newrelic_license_key }} "{{ newrelic_app_name }}" {{ newrelic_extra_params }}
  args:
    executable: /bin/bash
  register: command_result
  changed_when: command_result is defined and ("'newly installed' in command_result.stdout or 'Setting up' in command_result.stdout")
  when: ansible_os_family == 'RedHat'
