---
- name: Remove New Relic from Ubuntu
  apt:
    name:
      - newrelic*
    state: absent
    purge: true
  when: ansible_os_family == 'Debian'
  notify:
    - newrelic restart services

- name: Remove New Relic from Red Hat / CentOS / Amazon Linux
  yum:
    name:
      - newrelic-*
  when: ansible_os_family == 'RedHat'
  notify:
    - newrelic restart services
